# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Fox Girl"
license = "MIT"
licenselink = "https://github.com/tinyfluffs/hugo-fox-girl-theme/blob/main/LICENSE"
description = ""
homepage = "https://github.com/tinyfluffs/hugo-fox-girl-theme"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Ella Fox"
  homepage = "https://fox.gal"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
